### ISSUE TITLE
add split api?

### ISSUE THREAD

**Issue by lazyclaw-labs** [ssrlive/rust-tun#10]
I am wondering why we require mut self for read and write.
If this is the case, how can we read/write at the same time?
If this is not supported, I believe the use is very limited.

If mut self is really required, can we do a split to get a readhalf and writehalf? Just like what we did for streams?

**Comment by xmh0511** [comment]
Which read/write version do you refer to? The synchronous or asynchronous version? For the asynchronous version, just import `use futures::{SinkExt, StreamExt};`, then `framed` can be split to get a readhalf and writehalf.

The synchronous version for all platforms has a `split` function.

**Comment by lazyclaw-labs** [comment]
cool, Thanks.

**Comment by xmh0511** [comment]
fixed by https://github.com/ssrlive/rust-tun/pull/13
