### ISSUE TITLE
The default gateway is set/overwritten on Windows

### ISSUE THREAD

**Issue by M0dEx** [ssrlive/rust-tun#108]
The default gateway on Windows is always set/overwritten, regardless of any configuration options.

I don't think this is consistent default behaviour, as on every other platform, this library sets the needed routes for the interface and nothing else.

Is there a way to prevent this? If not, can such an option be added?

**Comment by ssrlive** [comment]
On your case, please delete this line and see the result?

https://github.com/tun2proxy/rust-tun/blob/2659aaa236c15007cfc76842f92406dc4762dd9b/src/platform/windows/device.rs#L79

**Comment by M0dEx** [comment]
It seems this somehow got fixed on its own without any version updates; might have been an environment issue on my part.

Sorry for the false alarm.
