### ISSUE TITLE
Async send and recv is not supported on Windows

### ISSUE THREAD

**Issue by AaronKutch** [ssrlive/rust-tun#109]
Hello, this crate almost works for my use case but is missing async support for Windows. I'm looking around and it seems like `wintun-bindings` needs async support within it first. Why is there a separate `wintun-bindings` fork from `wintun`? The original doesn't look unmaintained. How soon could this be implemented? I am considering doing it myself, but it would require a lot of research to get into.

**Comment by M0dEx** [comment]
The `AsyncWrite` and `AsyncRead` traits from Tokio are implemented on Windows, so you can just use those instead.

I agree it's a bit weird to have those and not the async `send` and `recv` methods as well.

**Comment by AaronKutch** [comment]
It requires workarounds because the `Async*` traits take a mutable reference while `send` and `recv` only need an immutable reference

**Comment by M0dEx** [comment]
You can always `tokio::io::split` the `AsyncDevice` if you want concurrent reads and writes.

**Comment by AaronKutch** [comment]
I have a wrapper struct that has `Arc<AsyncDevice>` and shares that around many task types that can both send and receive

**Comment by AaronKutch** [comment]
Oh and I should mention that there is no `set_nonblock` function on Windows, is this intended? Is it automatically set to nonblocking at the start for all platforms so I don't need it at all?

**Comment by ssrlive** [comment]
It's only be used at this line.

https://github.com/tun2proxy/rust-tun/blob/555661dfa74cc9f523819d196b12d0fc130f240d/src/async/unix_device.rs#L53

> Oh and I should mention that there is no `set_nonblock` function on Windows, is this intended? Is it automatically set to nonblocking at the start for all platforms so I don't need it at all?

**Comment by ssrlive** [comment]
I have no time to wait the review and merge for looooooooooooooooong time.

In fact, no one on the planet but me has the patience to contribute code to `wintun` anymore.

Furthermore, the `wintun` crate owner has rejected multiple requests from me to join as a co-contributor.

> Why is there a separate `wintun-bindings` fork from `wintun`?

**Comment by ssrlive** [comment]
You can read the implement of async here 

https://github.com/tun2proxy/wintun-bindings/blob/cd4df1a4297f4f6ba3b0bb55f04892e5163170be/src/async_session.rs#L66-L81

If you want to help implement recv and send, then you have to implement another set of logic, such as using `channel`s and other inter-thread communication methods. That would make the entire crate code very ugly.

> It requires workarounds because the `Async*` traits take a mutable reference while `send` and `recv` only need an immutable reference
