### ISSUE TITLE
Getting the network interface index for a device

### ISSUE THREAD

**Issue by AaronKutch** [ssrlive/rust-tun#110]
Currently, I use this crate by creating the interface, and looking up the interface by name and getting the ID so that I can use it in creating routes and other things. However, this is almost flaky in practice because of the way names are handled on different platforms and I would rather get the ID directly if that is possible. Or, are the low level details such that I should just search through the interface list and it would be just as efficient?

**Comment by ssrlive** [comment]
PR welcome.
