### ISSUE TITLE
Suggestion: Changing the type of mtu from usize to u16

### ISSUE THREAD

**Issue by SajjadPourali** [ssrlive/rust-tun#36]
As the tun interface operates on the network layer and above, I am not aware of any protocol that allows carrying more than 2^16 bytes in a single packet, which is the maximum value for an IP packet. The current implementation may lead some developers to choose the wrong value. Therefore, I suggest changing the mtu variable type from usize to u16 to prevent potential mistakes by developers.

**Comment by xmh0511** [comment]
Fixed by https://github.com/ssrlive/rust-tun/pull/38
