### ISSUE TITLE
How to generate GUID (Windows)

### ISSUE THREAD

**Issue by parthibx24** [ssrlive/rust-tun#60]
I need help generating the guid for the tun device. How can I check if an interface already exists with this guid?  Or is there any API to get the guid from the tun device after creating it for the first time (using `tun2::create_as_async`)

**Comment by ssrlive** [comment]
The GUID is no matter. Just keep the number of device will not changed while we set a GUID.
You can set any u128 number for it.

![image](https://github.com/tun2proxy/rust-tun/assets/30760636/6edcabb0-9c29-4409-a5d9-1267bd440824)
