### ISSUE TITLE
question on IOS

### ISSUE THREAD

**Issue by lazyclaw-labs** [ssrlive/rust-tun#68]
This is rather a IOS question instead of tun question, so it's a little bit out of topic here.

If I want to create a VPN in IOS, it seems like I do not need to create a tun at all? Since IOS has network extension, that can forward me the packets directly?

Thanks.

**Comment by ssrlive** [comment]
https://github.com/tun2proxy/rust-tun/blob/bb721ba79f5ad2d0869f1c3f4df670e44fa89a56/README.md?plain=1#L114-L134

**Comment by lazyclaw-labs** [comment]
So we don't actually assign an IP to it?

**Comment by ssrlive** [comment]
Why you want to assign an IP to it? I know you want to make a VPN app, you should select my `tun2proxy` rather than `tun2`.
