### ISSUE TITLE
Custom loading of wintun.dll should be a feature

### ISSUE THREAD

**Issue by cavivie** [ssrlive/rust-tun#75]
Custom loading of wintun.dll should be a feature that can reduce the dependence on libloading.

**Comment by cavivie** [comment]
@blechschmidt @ssrlive What do you think?

**Comment by ssrlive** [comment]
libloading crate is always in the dependencies list. so it's no matter.

**Comment by cavivie** [comment]
Forgive me for missing the context, we always use libloading to load wintun.dll, not only when customizing the path. Just close it.

**Comment by cavivie** [comment]
However, I think the current platform configuration default value does not obviously point to wintun.dll. Should we specify [the default value ](https://github.com/tun2proxy/rust-tun/blob/v2/src/platform/windows/mod.rs#L28) in the platform configuration instead of replacing a magic str [`wintun.dll`](https://github.com/tun2proxy/rust-tun/blob/v2/src/platform/windows/device.rs#L36) in device mod? In addition, [the path parameter](https://github.com/tun2proxy/rust-tun/blob/v2/src/platform/windows/mod.rs#L40) of custom_wintun_path should probably point to a string instead of option. If these arguments hold water, then I will make PRs for them.

**Comment by ssrlive** [comment]
OK. PR welcome.
