### ISSUE TITLE
Can this crate use a pre-existing TUN interface?

### ISSUE THREAD

**Issue by clark-ja** [ssrlive/rust-tun#79]
Can this crate use a pre-existing TUN interface or does it always have to generate a new one? If so, could you provide an usage example? Thank You!

**Comment by ssrlive** [comment]
https://github.com/tun2proxy/rust-tun/blob/cb57d8c1410aa1e2a012a50ff5c03d1db62f3f08/src/platform/linux/device.rs#L61-L64

Not implemented yet, PRs welcome.

**Comment by clark-ja** [comment]
Thanks for the quick reply. I'm going to take a look at it.

**Comment by ssrlive** [comment]
Supported in this commit. https://github.com/tun2proxy/rust-tun/commit/e0c7740dd111db04eb5a59162fe21407b8c7a81c 
Welcome to test it.
