### ISSUE TITLE
examples: ping-tun

### ISSUE THREAD

**Issue by kwsc98** [ssrlive/rust-tun#81]
test ping-tun  script，Will take effect randomly，some time use ping not work, but Restart script It will work
config
```
    config
        .address((10, 0, 0, 2))
        .netmask((255, 255, 0, 0))
        .destination((10, 0, 0, 1))
        .up();
```

**Comment by kwsc98** [comment]
[2024-06-23T12:44:41Z INFO  tun2::platform::macos::device] route -n add -net 10.0.0.2/16 10.0.0.1
macos

**Comment by ssrlive** [comment]
This is just a demonstration, the only one that is guaranteed to work correctly is this command: `ping 10.0.0.1`
