### ISSUE TITLE
Why windows platform MTU is always 65535?

### ISSUE THREAD

**Issue by feifeigood** [ssrlive/rust-tun#82]
Using tun2 created Wintun Interface MTU is always 65535
<img width="910" alt="image" src="https://github.com/tun2proxy/rust-tun/assets/5327802/33ffb06e-ebb9-4452-a754-04bdf358453f">

However, the MTU of the official client is configurable
![1591720404368_ pic](https://github.com/tun2proxy/rust-tun/assets/5327802/fae8e46e-bf02-42da-90b8-2e0a32993885)

Why this crates MTU can't be set on the Windows platform?

**Comment by ssrlive** [comment]
https://github.com/WireGuard/wintun/blob/master/driver/wintun.c#L1103

![image](https://github.com/tun2proxy/rust-tun/assets/30760636/27dc07d8-0123-4515-8968-bbc920b53194)

You can’t blame me for this disgusting setting.
