### ISSUE TITLE
SetInterfaceDnsSettings was not supported by older version of Windows

### ISSUE THREAD

**Issue by zonyitoo** [ssrlive/rust-tun#84]
ref shadowsocks/shadowsocks-rust#1589

> The procedure entry point SetInterfaceDnsSettings could not be located in the dynamic link library C:\Users\Administrator\Desktop\shadowsocks-rust-master\target\release\full\sslocal.exe.

It was introduced from https://github.com/tun2proxy/rust-tun/pull/74/files .

**Comment by zonyitoo** [comment]
This is a special feature provided by crate wintun: https://github.com/nulldotblack/wintun/blob/590481325c91debdd52afc2383d07ec9f5bc1523/src/util.rs#L88-L102 .

wintun.dll supports Windows 7, 8, 10, 11: https://git.zx2c4.com/wintun/about/ .

**Comment by ssrlive** [comment]
I'm not working on Windows now, can you provide a patch for it?

**Comment by ssrlive** [comment]
Since you lack the time and mind to maintain this project, could you add me as a co-contributor and publisher to this project?

**Comment by ssrlive** [comment]
You are right. but it's hard to commit patch to wintun crate, similar to `tun` crate.

https://learn.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-setinterfacednssettings#requirements

**Comment by zonyitoo** [comment]
Would you consider making `set_dns_servers` behind a `feature` gate? For example, adding a `feature = "dns_servers"`.

**Comment by ssrlive** [comment]
PR welcome, I will merge it in first time.
