### ISSUE TITLE
`AsyncDevice` does not expose `Device` methods

### ISSUE THREAD

**Issue by M0dEx** [ssrlive/rust-tun#92]
The `AsyncDevice` struct does not expose any of the inner `Device` methods, such as `name()`, `address()`, `mtu()` etc. This currently prevents users from leveraging a lot of the API in `async` codebases.

Could we either re-expose the methods (maybe using [delegate](https://crates.io/crates/delegate) or manually) or provide public access to the underlying device (possibly a lot simpler to implement)?

**Comment by ssrlive** [comment]
https://github.com/tun2proxy/rust-tun/blob/3644c33f6deb268564b77235d4c49b59eeed905d/src/async/unix_device.rs#L33-L45

**Comment by M0dEx** [comment]
> https://github.com/tun2proxy/rust-tun/blob/3644c33f6deb268564b77235d4c49b59eeed905d/src/async/unix_device.rs#L33-L45

Interesting, so if I made a function accepting `&Device` or `&mut Device`, I could access those methods, but if I just have an `AsyncDevice` instance, ~~I cannot~~ I have to call `.as_ref()`. That's a bit unergonomic, but sufficient.

Thanks!

**Comment by ssrlive** [comment]
I also think this API is a bit weird and I'm hoping you can come up with a more elegant solution.

**Comment by M0dEx** [comment]
I'll try to come up with something better, keeping this opened for reference.

**Comment by cavivie** [comment]
How about implementing `core::ops::Deref/DerefMut` traits for AsyncDevice trait?
```rust
impl core::ops::Deref for AsyncDevice {
    type Target = Device;

    fn deref(&self) -> &Self::Target {
        self.inner.get_ref()
    }
}

impl core::ops::DerefMut for AsyncDevice {
    fn deref_mut(&mut self) -> &mut Self::Target {
        self.inner.get_mut()
    }
}
```
